Repository themesberg/flowbite-react, pull requests merged in 2024-01, with the labels that each got.

#1206 feat(component): default to `type="text"` on `<TextInput>`
  src/components/TextInput/TextInput.tsx
Labels: :rocket: enhancement

#1215 Update with new year (2024)
  app/docs/[[...slug]]/page.tsx
  components/homepage/main-footer.tsx
  content/docs/getting-started/license.mdx
  src/components/Datepicker/helpers.spec.tsx
Labels: :books: documentation, testing

#1246 fix: homepage - use Link for internal links
  components/homepage/components-section.tsx
  components/homepage/hero-section/hero-section.tsx
  components/homepage/react-section.tsx
Labels: :books: documentation
