Repository themesberg/flowbite-react, pull requests merged in 2024-04, with the labels that each got.

#1336 fix(ui): build step + improve DX
  .changeset/fuzzy-ravens-type.md
  .changeset/old-flies-shop.md
  .github/actions/setup/action.yml
  .gitignore
  apps/storybook/package.json
  apps/web/package.json
  bun.lockb
  package.json
  packages/cli/package.json
  packages/ui/package.json
  packages/ui/tsconfig.build.json
Labels: :bug: bug, :rocket: enhancement, confirmed

#1339 fix: packages(ui) package.json types path
  .changeset/short-zoos-develop.md
  packages/ui/package.json
Labels: :bug: bug

#1351 chore: docs guides remix - upgrade from classic to vite
  apps/web/content/docs/guides/remix.mdx
Labels: :books: documentation

#1342 feat(component): add `<Drawer/>`
  apps/web/content/docs/components/drawer.mdx
  apps/web/data/docs-sidebar.ts
  apps/web/examples/drawer/drawer.backdrop.tsx
  apps/web/examples/drawer/drawer.bodyScrolling.tsx
  apps/web/examples/drawer/drawer.bottom.tsx
  apps/web/examples/drawer/drawer.contactForm.tsx
  apps/web/examples/drawer/drawer.formElements.tsx
  apps/web/examples/drawer/drawer.left.tsx
  apps/web/examples/drawer/drawer.navigation.tsx
  apps/web/examples/drawer/drawer.noBackdrop.tsx
  apps/web/examples/drawer/drawer.noBodyScrolling.tsx
  apps/web/examples/drawer/drawer.right.tsx
  apps/web/examples/drawer/drawer.root.tsx
  apps/web/examples/drawer/drawer.swipeableEdge.tsx
  apps/web/examples/drawer/drawer.top.tsx
  apps/web/examples/drawer/index.ts
  apps/web/examples/index.ts
  packages/ui/rollup.config.mjs
  packages/ui/src/components/Drawer/Drawer.spec.tsx
  packages/ui/src/components/Drawer/Drawer.stories.tsx
  packages/ui/src/components/Drawer/Drawer.tsx
  packages/ui/src/components/Drawer/DrawerContext.tsx
  packages/ui/src/components/Drawer/DrawerHeader.tsx
  packages/ui/src/components/Drawer/DrawerItems.tsx
  packages/ui/src/components/Drawer/index.ts
  packages/ui/src/components/Drawer/theme.ts
  packages/ui/src/components/Flowbite/FlowbiteTheme.ts
  packages/ui/src/index.ts
  packages/ui/src/theme.ts
Labels: :dart: new component

#1331 feat(component): add `<MegaMenu/>`
  apps/web/content/docs/components/mega-menu.mdx
  apps/web/data/docs-sidebar.ts
  apps/web/examples/index.ts
  apps/web/examples/megaMenu/index.ts
  apps/web/examples/megaMenu/megaMenu.fullWidth.tsx
  apps/web/examples/megaMenu/megaMenu.fullWidthCTA.tsx
  apps/web/examples/megaMenu/megaMenu.fullWidthImage.tsx
  apps/web/examples/megaMenu/megaMenu.icons.tsx
  apps/web/examples/megaMenu/megaMenu.root.tsx
  apps/web/public/dashboard-overview.png
  packages/ui/src/components/Flowbite/FlowbiteTheme.ts
  packages/ui/src/components/MegaMenu/MegaMenu.spec.tsx
  packages/ui/src/components/MegaMenu/MegaMenu.stories.tsx
  packages/ui/src/components/MegaMenu/MegaMenu.tsx
  packages/ui/src/components/MegaMenu/MegaMenuDropdown.tsx
  packages/ui/src/components/MegaMenu/MegaMenuDropdownToggle.tsx
  packages/ui/src/components/MegaMenu/index.ts
  packages/ui/src/components/MegaMenu/theme.ts
  packages/ui/src/index.ts
  packages/ui/src/theme.ts
Labels: :dart: new component

#1374 docs(drawer) - examples cleanup
  apps/web/examples/drawer/drawer.backdrop.tsx
  apps/web/examples/drawer/drawer.bodyScrolling.tsx
  apps/web/examples/drawer/drawer.bottom.tsx
  apps/web/examples/drawer/drawer.contactForm.tsx
  apps/web/examples/drawer/drawer.formElements.tsx
  apps/web/examples/drawer/drawer.left.tsx
  apps/web/examples/drawer/drawer.navigation.tsx
  apps/web/examples/drawer/drawer.noBackdrop.tsx
  apps/web/examples/drawer/drawer.noBodyScrolling.tsx
  apps/web/examples/drawer/drawer.right.tsx
  apps/web/examples/drawer/drawer.root.tsx
  apps/web/examples/drawer/drawer.swipeableEdge.tsx
  apps/web/examples/drawer/drawer.top.tsx
Labels: :books: documentation

#1376 Exclude analytics from `examples` page
  apps/web/app/layout.tsx
  apps/web/components/fathom-script.tsx
Labels: :bug: bug, :books: documentation
